### ISSUE TITLE
Pattern Lab and CMSs

### ISSUE THREAD

**Issue by petroleumjelliffe** [bradfrost/patternlab#12]
First off, I love Pattern Lab and the ideas behind atomic design.  

The current implementation works as a custom PHP application, which is well suited to a small static site.  Correct me if I'm wrong here.

How will this work with Wordpress or Drupal?  Is this compatible with those CMS's nested templates?  That is, can the atomic design approach, and Pattern Lab work side by side with existing CMS's or require a new CMS to be built with these principles in mind.  Nested templates are nothing new after all, and are essential to a scalable CMS.

**Comment by developher-net** [comment]
I look at this (and have used it) to do rapid prototypes of pages before implementing as a CMS. I think the inherited atomic approach results in "templates" that are logically separated, and make for easier integration into a CMS.

**Comment by petroleumjelliffe** [comment]
Thanks.  I'd like to discuss this further offline if that's ok.  I'm really interested to see if this leads not just to faster prototypes, but more realistic prototypes.  It also seems like a good way to reinforce web development standards and principles with more traditional graphic designers who can't quite design in code yet.

**Comment by bradfrost** [comment]
Thanks for the discussion! We're currently working on ways to make the
transition from templates to pages a lot easier and a whole lot more
dynamic.

Our plan is to use Mustache http://mustache.github.io/ to allow us to make
molecules and organisms a lot more dynamic so that we can easily drop in
real and/or representative data.

With these thoughts in mind, I suppose you could write something that would
pull in an RSS feed from the CMS and populate the appropriate
molecules/organisms/templates with real content.

---

Brad Frost
http://bradfrostweb.com
http://twitter.com/brad_frost

**Comment by joranovski** [comment]
Maybe a nice idea to combine it with http://laktek.github.io/punch/, you could even use http://handlebarsjs.com because punch already has those integrated. It's a pretty nice static generator

**Comment by dmolsen** [comment]
We're currently developing an almost dead simple static site generator (no command line necessary). We're also trying to break up the project in a logical way so that if someone wants to implement it for the own language/workflow it shouldn't be a big deal. We're getting closer to having a release candidate that we can share. This has been good feedback though.
